theme: jekyll-theme-cayman
title: Data Science Portfolio
description: Hello! My name is Milan Patty and I'm 21 years old. I am currently in my 4th semester in Information & Communication Technology at Fontys University of Applied Sciences in Eindhoven, the Netherlands.
